### ISSUE TITLE
hesap bulunamıyor

### ISSUE THREAD

**Issue by tufandayi42** [mustafa0kavak/IsBank#1]
![Screenshot_3](https://github.com/mustafa0kavak/IsBank/assets/93540793/fc287e3e-cb0f-44d9-be31-5f0d6975f10b)
![Screenshot_4](https://github.com/mustafa0kavak/IsBank/assets/93540793/7d86a888-8acb-4f36-98c6-65a797c29b72)

**Comment by mustafa0kavak** [comment]
Kısmen düzeltildi
